pipeline {
    agent any

    stages {
        stage('checkout_script') {
            steps {
                git changelog: false, credentialsId: '46d318e0-7de7-49ab-86ae-1669225823c1', poll: false, url: 'https://github.com/vekatkriish/apigee_2.git'
            }
        }
        stage('resolve_task') {
            steps {
                script{
                        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: '46d318e0-7de7-49ab-86ae-1669225823c1', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD']]) {
                             String encoded_password = java.net.URLEncoder.encode(env.GIT_PASSWORD, "UTF-8")
                             gitrepo = 'github.com/vekatkriish/apigee_2.git'
                             dir ('RallyBuild') {
                                isBranchExists = sh(script: 'git ls-remote --heads https://github.com/vekatkriish/apigee_2.git ${branchName} | wc -l', returnStdout: true).trim()
                                if(isBranchExists == 1){
                                    error 'branch '+ env.branchName +'already exixts'
                                }else{
                                    isLocalBranchExists = sh(script: 'git branch -a | grep ${branchName} | wc -l', returnStdout: true).trim()
                                    if(isLocalBranchExists == 1){
                                        echo 'found local git branch so, deleting to resolve ambiguity'
                                        sh 'git branch -d ${branchName}'
                                    }
                                    echo 'creating new branch ....'
                                    sh 'git branch ${branchName}'
                                    sh 'chmod +x gitcommit.sh'
                                    ret = sh(script: './gitcommit.sh '+ env.GIT_USERNAME +' '+encoded_password+' '+gitrepo+' '+ env.branchName, returnStdout: true).trim()
                                    echo 'Git Branch Commit & Push Status: '+ret
                                    if(ret == 'OK'){
                                        echo 'git branch ' + env.branchName + ' created'
                                    }else{
                                        error 'git unable to commit'
                                    }
                                }
                            }
                        }
                }
            }
        }
    }
    post {
        success {
            script{
                dir ('RallyBuild') {
                    sh 'python updateTask.py $fmtId $notes $BUILD_URL'
                }
            script{
                mail (to: env.notes.split(';')[0].trim(),
                     subject: 'Job '+env.JOB_NAME+' '+env.BUILD_NUMBER+' is sucesses',
                    body: "please visit {$BUILD_URL} for more details.");
            }
            }
        }
        failure {
            echo 'failed build'
        }
    }
}
