pipeline {
    agent any

    stages {
        stage('script_checkout') {
            steps {
                script{
                    git changelog: false, credentialsId: 'dfab18cc-f6ae-4d8e-abef-20bf702446bd', poll: false, url: 'http://laxmi@10.255.242.153:7990/scm/rt/rally-v1.git'
                }
            }
        }

        stage('initiate_builds') {
            steps {
                script{
                    dir ('RallyAutomation') {
                        sh 'chmod +x startPipeline.sh'
                        sh 'python readTickets.py US10'
                    }
                }

            }
        }
    }
}
